// flow-typed signature: e54f9b00be15ceb986fb411bad7b3584
// flow-typed version: <<STUB>>/exonum-client_v^0.12.3/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exonum-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exonum-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'exonum-client/dist/exonum-client' {
  declare module.exports: any;
}

declare module 'exonum-client/dist/exonum-client.min' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/blockchain/block' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/blockchain/index' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/blockchain/merkle-patricia' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/blockchain/merkle' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/blockchain/ProofPath' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/blockchain/transport' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/crypto/index' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/helpers' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/index' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/types/array' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/types/convert' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/types/generic' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/types/hexadecimal' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/types/index' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/types/message' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/types/primitive' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/types/serialization' {
  declare module.exports: any;
}

declare module 'exonum-client/lib/types/validate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'exonum-client/dist/exonum-client.js' {
  declare module.exports: $Exports<'exonum-client/dist/exonum-client'>;
}
declare module 'exonum-client/dist/exonum-client.min.js' {
  declare module.exports: $Exports<'exonum-client/dist/exonum-client.min'>;
}
declare module 'exonum-client/lib/blockchain/block.js' {
  declare module.exports: $Exports<'exonum-client/lib/blockchain/block'>;
}
declare module 'exonum-client/lib/blockchain/index.js' {
  declare module.exports: $Exports<'exonum-client/lib/blockchain/index'>;
}
declare module 'exonum-client/lib/blockchain/merkle-patricia.js' {
  declare module.exports: $Exports<'exonum-client/lib/blockchain/merkle-patricia'>;
}
declare module 'exonum-client/lib/blockchain/merkle.js' {
  declare module.exports: $Exports<'exonum-client/lib/blockchain/merkle'>;
}
declare module 'exonum-client/lib/blockchain/ProofPath.js' {
  declare module.exports: $Exports<'exonum-client/lib/blockchain/ProofPath'>;
}
declare module 'exonum-client/lib/blockchain/transport.js' {
  declare module.exports: $Exports<'exonum-client/lib/blockchain/transport'>;
}
declare module 'exonum-client/lib/crypto/index.js' {
  declare module.exports: $Exports<'exonum-client/lib/crypto/index'>;
}
declare module 'exonum-client/lib/helpers.js' {
  declare module.exports: $Exports<'exonum-client/lib/helpers'>;
}
declare module 'exonum-client/lib/index.js' {
  declare module.exports: $Exports<'exonum-client/lib/index'>;
}
declare module 'exonum-client/lib/types/array.js' {
  declare module.exports: $Exports<'exonum-client/lib/types/array'>;
}
declare module 'exonum-client/lib/types/convert.js' {
  declare module.exports: $Exports<'exonum-client/lib/types/convert'>;
}
declare module 'exonum-client/lib/types/generic.js' {
  declare module.exports: $Exports<'exonum-client/lib/types/generic'>;
}
declare module 'exonum-client/lib/types/hexadecimal.js' {
  declare module.exports: $Exports<'exonum-client/lib/types/hexadecimal'>;
}
declare module 'exonum-client/lib/types/index.js' {
  declare module.exports: $Exports<'exonum-client/lib/types/index'>;
}
declare module 'exonum-client/lib/types/message.js' {
  declare module.exports: $Exports<'exonum-client/lib/types/message'>;
}
declare module 'exonum-client/lib/types/primitive.js' {
  declare module.exports: $Exports<'exonum-client/lib/types/primitive'>;
}
declare module 'exonum-client/lib/types/serialization.js' {
  declare module.exports: $Exports<'exonum-client/lib/types/serialization'>;
}
declare module 'exonum-client/lib/types/validate.js' {
  declare module.exports: $Exports<'exonum-client/lib/types/validate'>;
}
