// flow-typed signature: 69bab1fb0b79c7114cd2b6b0504bc863
// flow-typed version: <<STUB>>/react-desktop_v^0.3.5/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-desktop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-desktop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-desktop/macOs' {
  declare module.exports: any;
}

declare module 'react-desktop/osx' {
  declare module.exports: any;
}

declare module 'react-desktop/src/animation/bezierEasing' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Box/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Box/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Button/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Button/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Button/windows/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Button/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Checkbox/macOs/Checkmark' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Checkbox/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Checkbox/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Checkbox/windows/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Checkbox/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/color' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Dialog/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Dialog/macOs/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Label/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Label/windows/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Link/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ListView/macOs/Footer/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ListView/macOs/Footer/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ListView/macOs/Header/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ListView/macOs/Header/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ListView/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ListView/macOs/Row/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ListView/macOs/Row/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ListView/macOs/Section/Header/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ListView/macOs/Section/Header/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ListView/macOs/Section/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ListView/macOs/Section/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ListView/macOs/Separator/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ListView/macOs/Separator/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ListView/macOs/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/MasterDetailsView/windows/Details/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/MasterDetailsView/windows/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/MasterDetailsView/windows/Item/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/MasterDetailsView/windows/Master/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/MasterDetailsView/windows/Pane' {
  declare module.exports: any;
}

declare module 'react-desktop/src/monitor' {
  declare module.exports: any;
}

declare module 'react-desktop/src/NavPane/windows/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/NavPane/windows/Item/Content/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/NavPane/windows/Item/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/NavPane/windows/Item/Title/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/NavPane/windows/Pane/Button/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/NavPane/windows/Pane/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/NavPane/windows/Pane/Item/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/NavPane/windows/Pane/style/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/NavPane/windows/style/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/os' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Pin/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Pin/macOs/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/placeholderStyle' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ProgressCircle/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ProgressCircle/macOs/progressCircleAnimation' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ProgressCircle/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ProgressCircle/windows/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ProgressCircle/windows/progressCircleAnimation' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ProgressCircle/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Radio/macOs/Circle' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Radio/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Radio/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Radio/windows/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Radio/windows/styles/windows' {
  declare module.exports: any;
}

declare module 'react-desktop/src/SearchField/macOs/cancelAnimation' {
  declare module.exports: any;
}

declare module 'react-desktop/src/SearchField/macOs/icons' {
  declare module.exports: any;
}

declare module 'react-desktop/src/SearchField/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/SearchField/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/SegmentedControl/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/SegmentedControl/macOs/Item/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/SegmentedControl/macOs/style/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/SegmentedControl/macOs/Tabs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/SegmentedControl/macOs/Tabs/Tab' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/alignment' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/background/macOs' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/background/windows' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/color/windows' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/dimension' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/fontSize' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/hidden' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/margin' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/padding' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/textAlign' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/theme/windows' {
  declare module.exports: any;
}

declare module 'react-desktop/src/style/width' {
  declare module.exports: any;
}

declare module 'react-desktop/src/styleHelper' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Text/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Text/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Text/windows/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Text/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TextArea/macOs/centerPlaceholderAnimation' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TextArea/macOs/focusRingAnimation' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TextArea/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TextArea/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TextArea/windows/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TextArea/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TextInput/macOs/centerPlaceholderAnimation' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TextInput/macOs/focusRingAnimation' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TextInput/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TextInput/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TextInput/windows/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TextInput/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TitleBar/macOs/Controls/Close' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TitleBar/macOs/Controls/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TitleBar/macOs/Controls/Minimize' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TitleBar/macOs/Controls/Resize' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TitleBar/macOs/Controls/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TitleBar/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TitleBar/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TitleBar/windows/Controls/Close' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TitleBar/windows/Controls/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TitleBar/windows/Controls/Maximize' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TitleBar/windows/Controls/Minimize' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TitleBar/windows/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/TitleBar/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Toolbar/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Toolbar/macOs/Nav/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Toolbar/macOs/Nav/Item/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/utils/mapStyles' {
  declare module.exports: any;
}

declare module 'react-desktop/src/ValueRef' {
  declare module.exports: any;
}

declare module 'react-desktop/src/View/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/View/windows/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Window/macOs/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Window/macOs/styles/10.11' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Window/windows/index' {
  declare module.exports: any;
}

declare module 'react-desktop/src/Window/windows/styles/windows10' {
  declare module.exports: any;
}

declare module 'react-desktop/src/windowFocus' {
  declare module.exports: any;
}

declare module 'react-desktop/windows' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-desktop/index' {
  declare module.exports: $Exports<'react-desktop'>;
}
declare module 'react-desktop/index.js' {
  declare module.exports: $Exports<'react-desktop'>;
}
declare module 'react-desktop/macOs.js' {
  declare module.exports: $Exports<'react-desktop/macOs'>;
}
declare module 'react-desktop/osx.js' {
  declare module.exports: $Exports<'react-desktop/osx'>;
}
declare module 'react-desktop/src/animation/bezierEasing.js' {
  declare module.exports: $Exports<'react-desktop/src/animation/bezierEasing'>;
}
declare module 'react-desktop/src/Box/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Box/macOs/index'>;
}
declare module 'react-desktop/src/Box/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/Box/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/Button/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Button/macOs/index'>;
}
declare module 'react-desktop/src/Button/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/Button/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/Button/windows/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Button/windows/index'>;
}
declare module 'react-desktop/src/Button/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/Button/windows/styles/windows10'>;
}
declare module 'react-desktop/src/Checkbox/macOs/Checkmark.js' {
  declare module.exports: $Exports<'react-desktop/src/Checkbox/macOs/Checkmark'>;
}
declare module 'react-desktop/src/Checkbox/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Checkbox/macOs/index'>;
}
declare module 'react-desktop/src/Checkbox/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/Checkbox/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/Checkbox/windows/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Checkbox/windows/index'>;
}
declare module 'react-desktop/src/Checkbox/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/Checkbox/windows/styles/windows10'>;
}
declare module 'react-desktop/src/color.js' {
  declare module.exports: $Exports<'react-desktop/src/color'>;
}
declare module 'react-desktop/src/Dialog/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Dialog/macOs/index'>;
}
declare module 'react-desktop/src/Dialog/macOs/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/Dialog/macOs/style/10.11'>;
}
declare module 'react-desktop/src/Label/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Label/macOs/index'>;
}
declare module 'react-desktop/src/Label/windows/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Label/windows/index'>;
}
declare module 'react-desktop/src/Link/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Link/macOs/index'>;
}
declare module 'react-desktop/src/ListView/macOs/Footer/index.js' {
  declare module.exports: $Exports<'react-desktop/src/ListView/macOs/Footer/index'>;
}
declare module 'react-desktop/src/ListView/macOs/Footer/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/ListView/macOs/Footer/style/10.11'>;
}
declare module 'react-desktop/src/ListView/macOs/Header/index.js' {
  declare module.exports: $Exports<'react-desktop/src/ListView/macOs/Header/index'>;
}
declare module 'react-desktop/src/ListView/macOs/Header/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/ListView/macOs/Header/style/10.11'>;
}
declare module 'react-desktop/src/ListView/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/ListView/macOs/index'>;
}
declare module 'react-desktop/src/ListView/macOs/Row/index.js' {
  declare module.exports: $Exports<'react-desktop/src/ListView/macOs/Row/index'>;
}
declare module 'react-desktop/src/ListView/macOs/Row/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/ListView/macOs/Row/style/10.11'>;
}
declare module 'react-desktop/src/ListView/macOs/Section/Header/index.js' {
  declare module.exports: $Exports<'react-desktop/src/ListView/macOs/Section/Header/index'>;
}
declare module 'react-desktop/src/ListView/macOs/Section/Header/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/ListView/macOs/Section/Header/style/10.11'>;
}
declare module 'react-desktop/src/ListView/macOs/Section/index.js' {
  declare module.exports: $Exports<'react-desktop/src/ListView/macOs/Section/index'>;
}
declare module 'react-desktop/src/ListView/macOs/Section/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/ListView/macOs/Section/style/10.11'>;
}
declare module 'react-desktop/src/ListView/macOs/Separator/index.js' {
  declare module.exports: $Exports<'react-desktop/src/ListView/macOs/Separator/index'>;
}
declare module 'react-desktop/src/ListView/macOs/Separator/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/ListView/macOs/Separator/style/10.11'>;
}
declare module 'react-desktop/src/ListView/macOs/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/ListView/macOs/style/10.11'>;
}
declare module 'react-desktop/src/MasterDetailsView/windows/Details/index.js' {
  declare module.exports: $Exports<'react-desktop/src/MasterDetailsView/windows/Details/index'>;
}
declare module 'react-desktop/src/MasterDetailsView/windows/index.js' {
  declare module.exports: $Exports<'react-desktop/src/MasterDetailsView/windows/index'>;
}
declare module 'react-desktop/src/MasterDetailsView/windows/Item/index.js' {
  declare module.exports: $Exports<'react-desktop/src/MasterDetailsView/windows/Item/index'>;
}
declare module 'react-desktop/src/MasterDetailsView/windows/Master/index.js' {
  declare module.exports: $Exports<'react-desktop/src/MasterDetailsView/windows/Master/index'>;
}
declare module 'react-desktop/src/MasterDetailsView/windows/Pane.js' {
  declare module.exports: $Exports<'react-desktop/src/MasterDetailsView/windows/Pane'>;
}
declare module 'react-desktop/src/monitor.js' {
  declare module.exports: $Exports<'react-desktop/src/monitor'>;
}
declare module 'react-desktop/src/NavPane/windows/index.js' {
  declare module.exports: $Exports<'react-desktop/src/NavPane/windows/index'>;
}
declare module 'react-desktop/src/NavPane/windows/Item/Content/index.js' {
  declare module.exports: $Exports<'react-desktop/src/NavPane/windows/Item/Content/index'>;
}
declare module 'react-desktop/src/NavPane/windows/Item/index.js' {
  declare module.exports: $Exports<'react-desktop/src/NavPane/windows/Item/index'>;
}
declare module 'react-desktop/src/NavPane/windows/Item/Title/index.js' {
  declare module.exports: $Exports<'react-desktop/src/NavPane/windows/Item/Title/index'>;
}
declare module 'react-desktop/src/NavPane/windows/Pane/Button/index.js' {
  declare module.exports: $Exports<'react-desktop/src/NavPane/windows/Pane/Button/index'>;
}
declare module 'react-desktop/src/NavPane/windows/Pane/index.js' {
  declare module.exports: $Exports<'react-desktop/src/NavPane/windows/Pane/index'>;
}
declare module 'react-desktop/src/NavPane/windows/Pane/Item/index.js' {
  declare module.exports: $Exports<'react-desktop/src/NavPane/windows/Pane/Item/index'>;
}
declare module 'react-desktop/src/NavPane/windows/Pane/style/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/NavPane/windows/Pane/style/windows10'>;
}
declare module 'react-desktop/src/NavPane/windows/style/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/NavPane/windows/style/windows10'>;
}
declare module 'react-desktop/src/os.js' {
  declare module.exports: $Exports<'react-desktop/src/os'>;
}
declare module 'react-desktop/src/Pin/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Pin/macOs/index'>;
}
declare module 'react-desktop/src/Pin/macOs/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/Pin/macOs/style/10.11'>;
}
declare module 'react-desktop/src/placeholderStyle.js' {
  declare module.exports: $Exports<'react-desktop/src/placeholderStyle'>;
}
declare module 'react-desktop/src/ProgressCircle/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/ProgressCircle/macOs/index'>;
}
declare module 'react-desktop/src/ProgressCircle/macOs/progressCircleAnimation.js' {
  declare module.exports: $Exports<'react-desktop/src/ProgressCircle/macOs/progressCircleAnimation'>;
}
declare module 'react-desktop/src/ProgressCircle/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/ProgressCircle/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/ProgressCircle/windows/index.js' {
  declare module.exports: $Exports<'react-desktop/src/ProgressCircle/windows/index'>;
}
declare module 'react-desktop/src/ProgressCircle/windows/progressCircleAnimation.js' {
  declare module.exports: $Exports<'react-desktop/src/ProgressCircle/windows/progressCircleAnimation'>;
}
declare module 'react-desktop/src/ProgressCircle/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/ProgressCircle/windows/styles/windows10'>;
}
declare module 'react-desktop/src/Radio/macOs/Circle.js' {
  declare module.exports: $Exports<'react-desktop/src/Radio/macOs/Circle'>;
}
declare module 'react-desktop/src/Radio/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Radio/macOs/index'>;
}
declare module 'react-desktop/src/Radio/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/Radio/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/Radio/windows/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Radio/windows/index'>;
}
declare module 'react-desktop/src/Radio/windows/styles/windows.js' {
  declare module.exports: $Exports<'react-desktop/src/Radio/windows/styles/windows'>;
}
declare module 'react-desktop/src/SearchField/macOs/cancelAnimation.js' {
  declare module.exports: $Exports<'react-desktop/src/SearchField/macOs/cancelAnimation'>;
}
declare module 'react-desktop/src/SearchField/macOs/icons.js' {
  declare module.exports: $Exports<'react-desktop/src/SearchField/macOs/icons'>;
}
declare module 'react-desktop/src/SearchField/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/SearchField/macOs/index'>;
}
declare module 'react-desktop/src/SearchField/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/SearchField/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/SegmentedControl/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/SegmentedControl/macOs/index'>;
}
declare module 'react-desktop/src/SegmentedControl/macOs/Item/index.js' {
  declare module.exports: $Exports<'react-desktop/src/SegmentedControl/macOs/Item/index'>;
}
declare module 'react-desktop/src/SegmentedControl/macOs/style/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/SegmentedControl/macOs/style/10.11'>;
}
declare module 'react-desktop/src/SegmentedControl/macOs/Tabs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/SegmentedControl/macOs/Tabs/index'>;
}
declare module 'react-desktop/src/SegmentedControl/macOs/Tabs/Tab.js' {
  declare module.exports: $Exports<'react-desktop/src/SegmentedControl/macOs/Tabs/Tab'>;
}
declare module 'react-desktop/src/style/alignment.js' {
  declare module.exports: $Exports<'react-desktop/src/style/alignment'>;
}
declare module 'react-desktop/src/style/background/macOs.js' {
  declare module.exports: $Exports<'react-desktop/src/style/background/macOs'>;
}
declare module 'react-desktop/src/style/background/windows.js' {
  declare module.exports: $Exports<'react-desktop/src/style/background/windows'>;
}
declare module 'react-desktop/src/style/color/windows.js' {
  declare module.exports: $Exports<'react-desktop/src/style/color/windows'>;
}
declare module 'react-desktop/src/style/dimension.js' {
  declare module.exports: $Exports<'react-desktop/src/style/dimension'>;
}
declare module 'react-desktop/src/style/fontSize.js' {
  declare module.exports: $Exports<'react-desktop/src/style/fontSize'>;
}
declare module 'react-desktop/src/style/hidden.js' {
  declare module.exports: $Exports<'react-desktop/src/style/hidden'>;
}
declare module 'react-desktop/src/style/margin.js' {
  declare module.exports: $Exports<'react-desktop/src/style/margin'>;
}
declare module 'react-desktop/src/style/padding.js' {
  declare module.exports: $Exports<'react-desktop/src/style/padding'>;
}
declare module 'react-desktop/src/style/textAlign.js' {
  declare module.exports: $Exports<'react-desktop/src/style/textAlign'>;
}
declare module 'react-desktop/src/style/theme/windows.js' {
  declare module.exports: $Exports<'react-desktop/src/style/theme/windows'>;
}
declare module 'react-desktop/src/style/width.js' {
  declare module.exports: $Exports<'react-desktop/src/style/width'>;
}
declare module 'react-desktop/src/styleHelper.js' {
  declare module.exports: $Exports<'react-desktop/src/styleHelper'>;
}
declare module 'react-desktop/src/Text/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Text/macOs/index'>;
}
declare module 'react-desktop/src/Text/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/Text/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/Text/windows/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Text/windows/index'>;
}
declare module 'react-desktop/src/Text/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/Text/windows/styles/windows10'>;
}
declare module 'react-desktop/src/TextArea/macOs/centerPlaceholderAnimation.js' {
  declare module.exports: $Exports<'react-desktop/src/TextArea/macOs/centerPlaceholderAnimation'>;
}
declare module 'react-desktop/src/TextArea/macOs/focusRingAnimation.js' {
  declare module.exports: $Exports<'react-desktop/src/TextArea/macOs/focusRingAnimation'>;
}
declare module 'react-desktop/src/TextArea/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/TextArea/macOs/index'>;
}
declare module 'react-desktop/src/TextArea/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/TextArea/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/TextArea/windows/index.js' {
  declare module.exports: $Exports<'react-desktop/src/TextArea/windows/index'>;
}
declare module 'react-desktop/src/TextArea/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/TextArea/windows/styles/windows10'>;
}
declare module 'react-desktop/src/TextInput/macOs/centerPlaceholderAnimation.js' {
  declare module.exports: $Exports<'react-desktop/src/TextInput/macOs/centerPlaceholderAnimation'>;
}
declare module 'react-desktop/src/TextInput/macOs/focusRingAnimation.js' {
  declare module.exports: $Exports<'react-desktop/src/TextInput/macOs/focusRingAnimation'>;
}
declare module 'react-desktop/src/TextInput/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/TextInput/macOs/index'>;
}
declare module 'react-desktop/src/TextInput/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/TextInput/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/TextInput/windows/index.js' {
  declare module.exports: $Exports<'react-desktop/src/TextInput/windows/index'>;
}
declare module 'react-desktop/src/TextInput/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/TextInput/windows/styles/windows10'>;
}
declare module 'react-desktop/src/TitleBar/macOs/Controls/Close.js' {
  declare module.exports: $Exports<'react-desktop/src/TitleBar/macOs/Controls/Close'>;
}
declare module 'react-desktop/src/TitleBar/macOs/Controls/index.js' {
  declare module.exports: $Exports<'react-desktop/src/TitleBar/macOs/Controls/index'>;
}
declare module 'react-desktop/src/TitleBar/macOs/Controls/Minimize.js' {
  declare module.exports: $Exports<'react-desktop/src/TitleBar/macOs/Controls/Minimize'>;
}
declare module 'react-desktop/src/TitleBar/macOs/Controls/Resize.js' {
  declare module.exports: $Exports<'react-desktop/src/TitleBar/macOs/Controls/Resize'>;
}
declare module 'react-desktop/src/TitleBar/macOs/Controls/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/TitleBar/macOs/Controls/styles/10.11'>;
}
declare module 'react-desktop/src/TitleBar/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/TitleBar/macOs/index'>;
}
declare module 'react-desktop/src/TitleBar/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/TitleBar/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/TitleBar/windows/Controls/Close.js' {
  declare module.exports: $Exports<'react-desktop/src/TitleBar/windows/Controls/Close'>;
}
declare module 'react-desktop/src/TitleBar/windows/Controls/index.js' {
  declare module.exports: $Exports<'react-desktop/src/TitleBar/windows/Controls/index'>;
}
declare module 'react-desktop/src/TitleBar/windows/Controls/Maximize.js' {
  declare module.exports: $Exports<'react-desktop/src/TitleBar/windows/Controls/Maximize'>;
}
declare module 'react-desktop/src/TitleBar/windows/Controls/Minimize.js' {
  declare module.exports: $Exports<'react-desktop/src/TitleBar/windows/Controls/Minimize'>;
}
declare module 'react-desktop/src/TitleBar/windows/index.js' {
  declare module.exports: $Exports<'react-desktop/src/TitleBar/windows/index'>;
}
declare module 'react-desktop/src/TitleBar/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/TitleBar/windows/styles/windows10'>;
}
declare module 'react-desktop/src/Toolbar/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Toolbar/macOs/index'>;
}
declare module 'react-desktop/src/Toolbar/macOs/Nav/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Toolbar/macOs/Nav/index'>;
}
declare module 'react-desktop/src/Toolbar/macOs/Nav/Item/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Toolbar/macOs/Nav/Item/index'>;
}
declare module 'react-desktop/src/utils/mapStyles.js' {
  declare module.exports: $Exports<'react-desktop/src/utils/mapStyles'>;
}
declare module 'react-desktop/src/ValueRef.js' {
  declare module.exports: $Exports<'react-desktop/src/ValueRef'>;
}
declare module 'react-desktop/src/View/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/View/macOs/index'>;
}
declare module 'react-desktop/src/View/windows/index.js' {
  declare module.exports: $Exports<'react-desktop/src/View/windows/index'>;
}
declare module 'react-desktop/src/Window/macOs/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Window/macOs/index'>;
}
declare module 'react-desktop/src/Window/macOs/styles/10.11.js' {
  declare module.exports: $Exports<'react-desktop/src/Window/macOs/styles/10.11'>;
}
declare module 'react-desktop/src/Window/windows/index.js' {
  declare module.exports: $Exports<'react-desktop/src/Window/windows/index'>;
}
declare module 'react-desktop/src/Window/windows/styles/windows10.js' {
  declare module.exports: $Exports<'react-desktop/src/Window/windows/styles/windows10'>;
}
declare module 'react-desktop/src/windowFocus.js' {
  declare module.exports: $Exports<'react-desktop/src/windowFocus'>;
}
declare module 'react-desktop/windows.js' {
  declare module.exports: $Exports<'react-desktop/windows'>;
}
